import {Dimensions, StyleSheet} from 'react-native';
import {hp} from '../../Helpers/responsive-ratio';
import {fonts, os, palette} from '../../Theme/Index';
const SCREEN_HEIGHT = Dimensions.get('window').height;
const SCREEN_WIDTH = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#393939',
    flex: 1,
  },
  qrContainer: {
    justifyContent: 'center',
    backgroundColor: '#393939',
    alignItems: 'center',
  },

  cameraStyle: {
    height: 230,
    width: 257,
    backgroundColor: '#393939',
    borderRadius: os?.ios ? 30 : 50,
    overflow: 'hidden',
  },
  qrImage: {
    width: 220,
    height: 230,
  },
  rectangleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '90%',
    // backgroundColor: 'yellow',
  },
  rectangle: {
    backgroundColor: 'transparent',
    height: SCREEN_HEIGHT * 0.48,
  },
  qrImageInner: {
    width: 170,
    height: 170,
    resizeMode: 'contain',
    position: 'absolute',
    zIndex: 999,
    left: 30,
    top: 60,
    // backgroundColor: palette.white,
  },
  innerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height - hp(30),
    backgroundColor: '#393939',
    borderRadius: 50,
  },
  Qrscan: {
    fontFamily: fonts?.regular,
    fontSize: 18,
    color: '#fafafa',
    fontWeight: '400',
  },
  bottomLefttEdge: {
    borderWidth: 5,
    height: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    left: 60,
    bottom: 180,
  },
  bottomBaseEdge: {
    borderWidth: 5,
    width: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    left: 60,
    bottom: 180,
  },
  topLeftEdge: {
    borderWidth: 5,
    height: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    left: 60,
    top: 175,
  },
  topBaseEdge: {
    borderWidth: 5,
    width: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    left: 60,
    top: 175,
  },
  markLine: {
    height: 3,
    width: 220,
    backgroundColor: 'red',
  },
  bottomRighttEdge: {
    borderWidth: 5,
    width: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    right: 60,
    bottom: 180,
  },
  bottomBaseRightEdge: {
    borderWidth: 5,
    height: 50,
    borderColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    right: 60,
    bottom: 180,
    borderRadius: 50,
  },
  topRighttEdge: {
    borderWidth: 5,
    height: 50,
    borderColor: 'black',
    backgroundColor: 'black',

    position: 'absolute',
    zIndex: 999999,
    right: 60,
    top: 175,
    borderTopRightRadius: 100,
    // borderRadius: 50,
  },
  topBaseRightEdge: {
    borderWidth: 5,
    width: 50,
    borderColor: 'black',
    backgroundColor: 'black',
    position: 'absolute',
    zIndex: 999999,
    right: 60,
    top: 175,
    borderTopRightRadius: 100,
  },
  qrCode: {
    marginTop: 20,
    backgroundColor: palette.white,
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  modal: {
    width: '100%',
    margin: 0,
    justifyContent: 'flex-end',
  },
  modalView: {
    backgroundColor: 'white',
    borderTopRightRadius: 35,
    borderTopLeftRadius: 35,
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  scannedTxt: {
    fontFamily: fonts.semibold,
    fontSize: 16,
    color: palette.black,
    marginBottom: 20,
    lineHeight: 21,
  },
  desTxt: {
    fontFamily: fonts.medium,
    fontSize: 14,
    color: '#616161',
    marginBottom: '20%',
  },
  btnBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
});
