import {StyleSheet, Dimensions, TouchableOpacity, Platform} from 'react-native';
import {createBox, createText, createTheme} from '@shopify/restyle';
import {wp} from '../Helpers/responsive-ratio';
const {width, height} = Dimensions.get('window');

export const size = {
  //Primary
  width: width,
  height: height,
};
export const os = {
  ios: Platform.OS == 'ios',
};
export const palette = {
  //Primary
  primary: '#FA5000',
  primary1: '#6cb9d6',
  primary2: '#FFEEE6',
  primary3: '#FDC9B0',

  //Black Shade
  blackshade: '#262626',
  blackshade1: '#737373',
  blackshade2: '#2d2d2d',
  blackshade3: '#333333',
  //Destructive
  destructive: '#EF4444',

  // Secondary
  secondary: '#CED4FD',
  secondary1: '#F5F6FF',
  secondary2: '#E0E0FD',

  //Tertiary
  tertiary: '#F4F5F7',
  tertiary1: '#CCCCD5',
  tertiary2: '#D4D4D4',
  tertiary3: '#B6B4B4',
  tertiary4: '#737373',

  support4: '#525252',

  //Supporting colos
  support: '#172B3D',
  support1: '#212121',
  support2: '#0F0250',

  // App colors
  black: 'rgb(26, 26, 26)',
  inputBorder: '#E5E5E5',
  placeholder: '#A3A3A3',
  white: '#ffffff',
  greyishBrown: '#3D3D3D',
  red: '#ce1212',
  overlay: 'rgba(0, 0, 0, 0.1)',
  border: 'rgba(0,0,0,.4)',
  warmGrey: '#808080',
  whiteShade: 'rgb(246, 246, 246)',
  background: 'rgb(251,251,251)',
  greyText: '#646464',
  smokeWhite: '#fafafa',

  green: '#16A34A',
  lightGreen: '#22C55E',
  tertiary5: '#171717',
  transparent: '#00000070',
};

export const TypographyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  cardShadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  grow: {
    flexGrow: 1,
  },
  card: {
    minHeight: 175,
    backgroundColor: 'white',
    borderRadius: 25,
    marginHorizontal: 30,
  },
});
export const fonts = {
  bold: 'Poppins-Bold',
  semibold: 'Poppins-SemiBold',
  medium: 'Poppins-Medium',
  light: 'Poppins-Light',
  thin: 'Poppins-Thin',
  thinitalic: 'Poppins-ThinItalic',
  mediumItalic: 'Poppins-MediumItalic',
  regular: 'Poppins-Regular',
  italicLight: 'Poppins-LightItalic',
  italicBlack: 'Poppins-BlackItalic',
  boldItalic: 'Poppins-BoldItalic',
  italic: 'Poppins-Italic',
  black: 'Poppins-Black',
};

const theme = createTheme({
  colors: {
    white: 'white',
    black: 'black',
    red: 'red',
    //Primary
    primary: '#FA5000',
    primary1: '#6cb9d6',
    primary2: palette.primary2,
    primary3: palette.primary3,

    support4: palette?.support4,

    // Black shade
    blackshade: palette?.blackshade,
    blackshade1: palette?.blackshade1,
    blackshade2: palette.blackshade2,
    blackshade3: palette.blackshade3,

    //Destructive
    destructive: palette.destructive,

    // Secondary
    secondary: palette.secondary,
    secondary1: palette.secondary1,
    secondary2: palette.secondary2,

    //placeholder
    placeholder: palette.placeholder,

    //Tertiary
    tertiary: palette.tertiary,
    tertiary1: palette.tertiary1,
    tertiary2: palette.tertiary2,
    tertiary3: palette.tertiary3,
    tertiary4: palette.tertiary4,
    border: palette?.border,
    inputBorder: palette?.inputBorder,
    //Supporting colos
    lightGreen: palette?.lightGreen,
    support: 'support',
    support1: 'support1',
    support2: 'support2',
    warmGrey: 'warmGrey',
    smokeWhite: palette?.smokeWhite,
    green: palette?.green,
    tertiary5: palette?.tertiary5,
    transparent: palette?.transparent,
  },
  spacing: {
    xs: 1,

    vs: 3,
    s: 5,
    sm: 7,
    m: 10,
    mt: 12,
    t: 15,
    l: 20,
    xl: 25,
    xxl: 50,
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
  textVariants: {
    defaults: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.bold,
      color: 'black',
    },
    white24600: {
      fontSize: 24,
      fontWeight: '600',
      fontFamily: fonts.bold,
      color: 'white',
    },
    white24600: {
      fontSize: 24,
      fontWeight: '600',
      fontFamily: fonts.bold,
      color: 'white',
      lineHeight: 32,
    },
    blackshade28500: {
      fontSize: 28,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 36,
    },
    blackshade12900: {
      fontSize: 12,
      fontWeight: '900',
      fontFamily: fonts.bold,
      color: 'blackshade',
      lineHeight: 20,
      letterSpacing: 1,
    },
    primary28600: {
      fontSize: 28,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'primary',
      lineHeight: 36,
    },
    primary28700: {
      fontSize: 28,
      fontWeight: '700',
      fontFamily: fonts.bold,
      color: 'primary',
      lineHeight: 44,
    },

    blackshade20500: {
      fontSize: 20,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 28,
    },
    black16800: {
      fontSize: 16,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'black',
      lineHeight: 10,
    },
    lightGreen14600: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'lightGreen',
      //lineHeight: 22,
    },
    lightGreen16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'lightGreen',
    },
    support412600: {
      fontSize: 12,
      fontWeight: '600',
      fontFamily: fonts.regular,
      color: 'support4',
      //lineHeight: 22,
    },
    support414600: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.regular,
      color: 'support4',
      //lineHeight: 22,
    },
    support414600Regular: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.regular,
      color: 'support4',
      //lineHeight: 22,
    },
    support414600black: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.black,
      color: 'support4',
      //lineHeight: 22,
    },
    tertiary514900: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 20,
    },
    tertiary514900Medium: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 20,
    },
    primary32500: {
      fontSize: 32,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    blackshade8800: {
      fontSize: 8,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 10,
    },
    blackshade16400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade16600: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: fonts.bold,
      color: 'blackshade',
      lineHeight: 22,
    },

    blackshade16800Regular: {
      fontSize: 16,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade316800Regular: {
      fontSize: 16,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'blackshade3',
      lineHeight: 22,
    },
    blackshade16800: {
      fontSize: 16,
      fontWeight: '800',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
    },
    blackshade16800Semi: {
      fontSize: 16,
      fontWeight: '800',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 24,
    },
    tertiary412400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'tertiary4',
      lineHeight: 16,
    },
    blackshade112500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade112400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade110400: {
      fontSize: 10,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 11,
    },
    tertiary312500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'tertiary3',
      lineHeight: 22,
    },
    placeholder12400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'placeholder',
      //lineHeight: 22,
    },
    placeholder14400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'placeholder',
      //lineHeight: 22,
    },
    placeholder16400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'placeholder',
      //lineHeight: 22,
    },
    green14400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'green',
      //lineHeight: 22,
    },
    blackshade116400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade116500Regular: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade116500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade116600: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade14400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade15400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade14500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 20,
    },
    white14500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 20,
    },
    blackshade14600: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade14800: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade14800Medium: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade14800Semi: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade112500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 16,
    },
    blackshade114800: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 16,
    },
    blackshade114800Regular: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 16,
    },
    blackshade12500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 16,
    },
    blackshade13500: {
      fontSize: 13,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 16,
    },
    blackshade12400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 16,
    },
    blackshade20800Medium: {
      fontSize: 20,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
    },
    primary12Regular: {
      fontSize: 12,
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary14500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary14500Black: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.black,
      color: 'primary',
    },
    primary10500: {
      fontSize: 10,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary16500Medium: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
    },
    blackshade114400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade114500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    white14400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'white',
      lineHeight: 20,
    },
    white12Medium: {
      fontSize: 12,
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 20,
    },
    white14Medium: {
      fontSize: 14,
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 20,
    },
    smokeWhite16400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'smokeWhite',
      lineHeight: 22,
    },
    destructive16400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'destructive',
      lineHeight: 22,
    },
    blackshade18400: {
      fontSize: 18,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18Medium: {
      fontSize: 18,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800Regular: {
      fontSize: 18,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800: {
      fontSize: 18,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800Medium: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 24,
    },
    primary36500: {
      fontSize: 36,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    black36800: {
      fontSize: 36,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'black',
    },

    black16800: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'black',
      lineHeight: 10,
    },
    blackshade8800: {
      fontSize: 8,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 10,
    },
    blackshade16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      // lineHeight: 22,
    },
    blackshade16800Regular: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade316800Regular: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade3',
      lineHeight: 22,
    },
    blackshade16800: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 22,
    },
    blackshade16600Semi: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade112500: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    tertiary312500: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'tertiary3',
      lineHeight: 22,
    },
    placeholder12400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'placeholder',
      //lineHeight: 22,
    },
    blackshade116500Regular: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade116500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade24500: {
      fontSize: 24,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 32,
    },
    blackshade14800: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade14800Semi: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 20,
    },
    blackshade112500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 16,
    },
    blackshade12400: {
      fontSize: 12,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 16,
    },
    primary12Regular: {
      fontSize: 12,
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary14500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary14500Medium: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
    },
    primary16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    primary16500Medium: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
    },
    blackshade114400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade114500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'blackshade1',
      lineHeight: 22,
    },
    white18500Medium: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 24,
    },
    white12Medium: {
      fontSize: 12,
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 20,
    },
    white14Medium: {
      fontSize: 14,
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 20,
    },
    white16500: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'white',
      lineHeight: 22,
    },
    white16500regular: {
      fontSize: 16,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'white',
      lineHeight: 22,
    },
    blackshade18400: {
      fontSize: 18,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade20800Regular: {
      fontSize: 20,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 28,
    },
    blackshade18Medium: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800Regular: {
      fontSize: 18,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800: {
      fontSize: 18,
      fontWeight: '600',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18Bold: {
      fontSize: 18,
      fontWeight: 'bold',
      fontFamily: fonts.semibold,
      color: 'blackshade',
      lineHeight: 24,
    },
    blackshade18800Medium: {
      fontSize: 18,
      fontWeight: '600',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 24,
    },
    primary36500: {
      fontSize: 36,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    black36800: {
      fontSize: 36,
      fontWeight: '800',
      fontFamily: fonts.regular,
      color: 'black',
    },
    primary24500: {
      fontSize: 24,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
      lineHeight: 32,
    },
    primary20900: {
      fontSize: 20,
      fontWeight: '800',
      fontFamily: fonts.semibold,
      color: 'primary',
      lineHeight: 32,
      letterSpacing: 13,
    },
    tertiary16400: {
      fontSize: 16,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'tertiary4',
      lineHeight: 22,
    },
    tertiary14500: {
      fontSize: 14,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'tertiary4',
      lineHeight: 22,
    },
    primary36700: {
      fontSize: 36,
      fontWeight: '700',
      fontFamily: fonts.bold,
      color: 'primary',
      lineHeight: 44,
    },
    primary36700Medium: {
      fontSize: 36,
      fontWeight: '700',
      fontFamily: fonts.medium,
      color: 'primary',
      lineHeight: 44,
    },
    primary18500Medium: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
    },
    blackshade118500: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 22,
    },
    blackshade18500: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'blackshade',
      lineHeight: 24,
    },
    black36500: {
      fontSize: 36,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'black',
    },
    primary12500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
      lineHeight: 16,
    },
    white12500: {
      fontSize: 12,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'white',
      lineHeight: 16,
    },
    destructive14400: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: fonts.regular,
      color: 'destructive',
      lineHeight: 20,
    },
    blackshade12800: {
      fontSize: 12,
      fontWeight: '800',
      fontFamily: fonts.medium,
      color: 'blackshade',
      lineHeight: 20,
    },
    primary12900: {
      fontSize: 12,
      fontWeight: '900',
      fontFamily: fonts.regular,
      color: 'primary',
    },
    blackshade112900: {
      fontSize: 12,
      fontWeight: '900',
      fontFamily: fonts.medium,
      color: 'blackshade1',
      lineHeight: 16,
    },
    white36700: {
      fontSize: 36,
      fontWeight: '700',
      fontFamily: fonts.bold,
      color: 'white',
      lineHeight: 44,
    },
    white18500: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: fonts.regular,
      color: 'white',
      lineHeight: 24,
    },
    primary28500: {
      fontSize: 28,
      fontWeight: '500',
      fontFamily: fonts.medium,
      color: 'primary',
      lineHeight: 36,
    },
    primary14900: {
      fontSize: 14,
      fontWeight: '900',
      fontFamily: fonts.regular,
      color: 'primary',
      lineHeight: 20,
    },
  },
});

export const Text = createText();
export const Box = createBox();
export const TouchableBox = createBox(TouchableOpacity);

export type Theme = typeof theme;
export default theme;
